---

# (Public) domain where the application can be reached
opennotificaties_domain: notificaties.test.openzaak.nl

# Django config parameters
opennotificaties_secret_key: override-me

opennotificaties_db_username: opennotificaties
opennotificaties_db_password: opennotificaties
opennotificaties_db_host: localhost
opennotificaties_db_port: 5432
opennotificaties_db_name: opennotificaties

opennotificaties_sentry_dsn: null

opennotificaties_cache_db: 0

# Kubernetes namespace to run in
opennotificaties_namespace: opennotificaties-test

opennotificaties_version: latest
opennotificaties_image: openzaak/open-notificaties:{{ opennotificaties_version }}
opennotificaties_replicas: 3
opennotificaties_worker_replicas: 3
opennotificaties_instance: test

opennotificaties_rabbitmq:
  user: "opennotificaties-{{ opennotificaties_instance }}"
  password: "opennotificaties-{{ opennotificaties_instance }}"

opennotificaties_publish_broker_url: "amqp://{{ opennotificaties_rabbitmq.user }}:{{ opennotificaties_rabbitmq.password }}@rabbitmq:5672/%2F"
opennotificaties_celery_broker_url: "amqp://{{ opennotificaties_rabbitmq.user }}:{{ opennotificaties_rabbitmq.password }}@rabbitmq:5672//"
opennotificaties_celery_result_backend: "{{ opennotificaties_celery_broker_url }}"
