---

- name: Run the cache service
  docker_container:
    name: cache
    image: redis:5
    pull: yes
    hostname: cache
    restart_policy: always
    networks:
      - name: openzaak
    purge_networks: yes
    networks_cli_compatible: yes

- name: Run the OpenZaak backend service
  docker_container:
    name: openzaak
    image: openzaak/open-zaak:latest
    pull: yes
    hostname: openzaak
    restart_policy: always
    networks:
      - name: openzaak
    purge_networks: yes
    networks_cli_compatible: yes
    volumes:
      - /var/run/postgresql:/var/run/postgresql
      - openzaak-private-media:/app/private-media
    ports:
      - "127.0.0.1:8000:8000"
    env:
      # Obviously these secrets are not for real environments, or I would've
      # put them in the Ansible vault :-)
      DB_HOST: /var/run/postgresql
      DB_NAME: openzaak
      DB_USER: openzaak
      DB_PASSWORD: openzaak
      SECRET_KEY: '6$%s!#l2*y@5f!^^jx2wtr_4s-o#_d)g0g#1pw0lx=gqw^#%a_'
      ALLOWED_HOSTS: "localhost,{{ inventory_hostname }}"
      CACHE_DEFAULT: cache:6379/0
      CACHE_AXES: cache:6379/0
