dist: xenial

language: python

cache: pip

python: 3.7

services:
  - postgresql
  - docker

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10-postgis-2.4

env:
  global:
  - DJANGO_SETTINGS_MODULE=openzaak.conf.test
  - SECRET_KEY=dummy
  - DB_PASSWORD=
  - DB_USER=postgres

before_install:
  - sudo apt-get update
  - sudo apt-get install libgdal-dev gdal-bin
  - gdal-config --version

install:
  - pip install -r requirements/test.txt
  - pip install codecov isort black
  - npm ci
  - npm run build

before_script:
  - psql -U postgres -c "create extension postgis"

jobs:
  include:
    # Run jobs in parallel in stage Tests
    - stage: Tests
      name: "Django tests"
      script:
        - python src/manage.py collectstatic --noinput --link
        - coverage run src/manage.py test src

    - name: isort
      before_install: skip
      install:
        - pip install isort
      before_script: skip
      script: isort --recursive --check-only --diff .

    - name: black
      before_install: skip
      install:
        - pip install black
      before_script: skip
      script: black --check src

    - name: Test docker image build
      before_install: skip
      install: skip
      before_script: skip
      script: docker build .

    # TODO: second stage to push resulting image

after_success:
  - codecov
