dist: xenial

language: python

cache: pip

python: 3.7

services:
  - postgresql
  - docker

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10-postgis-2.4

env:
  global:
  - DJANGO_SETTINGS_MODULE=openzaak.conf.ci
  - DB_PASSWORD=
  - DB_USER=postgres
  - ALLOWED_HOSTS=openzaak.nl

before_install:
  - sudo apt-get update
  - sudo apt-get install libgdal-dev gdal-bin
  - gdal-config --version
  # https://github.com/travis-ci/travis-ci/issues/8920
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"

install:
  - pip install -r requirements/ci.txt
  - pip install codecov
  - npm ci
  - npm run build

before_script:
  - psql -U postgres -c "create extension postgis"
  # https://github.com/travis-ci/travis-ci/issues/8982#issuecomment-354357640
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"

jobs:
  include:
    # Run jobs in parallel in stage Tests
    - stage: Tests
      name: "Django tests"
      script:
        - python src/manage.py collectstatic --noinput --link
        - coverage run src/manage.py test src

    - name: isort
      before_install: skip
      install:
        - pip install isort
      before_script: skip
      script: isort --recursive --check-only --diff .

    - name: black
      before_install: skip
      install:
        - pip install black
      before_script: skip
      script: black --check src

    - name: Test docker image build
      before_install: skip
      install: skip
      before_script: skip
      script: docker build .

    - stage: Newman tests
      language: node_js
      node_js:
        - 8
      name: ZGW api tests
      services:
        - docker
      before_install: skip
      install:
        - npm install newman
      before_script: skip
      script:
        - docker-compose -f docker-compose.travis.yml up -d
        - bin/postman_tests.sh
      after_script:
        - docker-compose stop
        - docker-compose rm -f

    - stage: Push Docker image(s)
      before_install: skip
      install: skip
      before_script: skip
      script: skip
      after_success: skip
      deploy:
        - provider: script
          script: bin/docker_push.sh latest
          on:
            branch: master

        - provider: script
          script: bin/docker_push.sh $TRAVIS_TAG
          on:
            tags: true

after_success:
  - codecov
