dist: xenial

sudo: required

language: python

python: 3.7

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10-postgis-2.4

env:
  global:
  - DJANGO_SETTINGS_MODULE=openzaak.conf.test
  - SECRET_KEY=dummy
  - DB_PASSWORD=
  - DB_USER=postgres

before_install:
  - sudo apt-get update
  - sudo apt-get install libgdal-dev gdal-bin
  - gdal-config --version

install:
  - pip install -r requirements/test.txt
  - pip install codecov isort black
  - npm ci
  - npm run build

before_script:
  - psql -U postgres -c "create extension postgis"

jobs:
  include:
    - stage: django test
      script:
        - python src/manage.py collectstatic --noinput --link
        - coverage run src/manage.py test src

    - stage: isort
      script: isort --recursive --check-only --diff .

    - stage: black
      script: black --check src

after_success:
  - codecov
