---
# Overrides of role defaults
openzaak_secret_key: 'SOME-RANDOM-SECRET'
openzaak_db_name: openzaak-test
openzaak_db_host: "{{ db.host }}"
openzaak_db_port: "{{ db.port }}"
openzaak_db_username: openzaak-test
openzaak_db_password: SUPER-SECRET
