---

# Prepare the database: ensure the database exists and has the required
# extensions configured + set up a db user.

- name: Set up the database user
  postgresql_user:
    name: "{{ db_user.username }}"
    password: "{{ db_user.password }}"
    state: present

    login_host: "{{ db.host }}"
    port: "{{ db.port }}"
    login_user: "{{ db_superuser.username }}"
    login_password: "{{ db_superuser.password }}"

- name: Add application role to superuser
  postgresql_membership:
    group: "{{ db_user.username }}"
    target_roles:
      - "{{ db_superuser.username }}"
    state: present

    login_host: "{{ db.host }}"
    port: "{{ db.port }}"
    login_user: "{{ db_superuser.username }}"
    login_password: "{{ db_superuser.password }}"

- name: Set up the application database
  postgresql_db:
    name: "{{ db.name }}"
    owner: "{{ db_user.username }}"
    state: present

    login_host: "{{ db.host }}"
    port: "{{ db.port }}"
    login_user: "{{ db_superuser.username }}"
    login_password: "{{ db_superuser.password }}"

- name: Enable the required database extensions
  postgresql_ext:
    name: "{{ item }}"
    db: "{{ db.name }}"
    state: present

    login_host: "{{ db.host }}"
    port: "{{ db.port }}"
    login_user: "{{ db_superuser.username }}"
    login_password: "{{ db_superuser.password }}"
  with_items:
    - postgis
    - pg_trgm
