---

- name: Deploy the Open Zaak apps in the cluster
  hosts: localhost

  vars:
    # FIXME
    ansible_python_interpreter: /home/bbt/.virtualenvs/open-zaak/bin/python

  vars_files:
    - vars/db_credentials.yml

  roles:
    - role: openzaak
      vars:
        db_host: "{{ db.host }}"
        db_port: "{{ db.port }}"
        db_name: "{{ db.name }}"
        db_username: "{{ db_user.username }}"
        db_password: "{{ db_user.password }}"
