---

- name: Deploy the Open Zaak apps in the cluster
  hosts: localhost

  vars:
    # FIXME
    ansible_python_interpreter: /home/bbt/.virtualenvs/open-zaak/bin/python

  vars_files:
    - vars/db_credentials.yml
    - vars/openzaak.yml
    - vars/opennotificaties.yml

  roles:
    - role: openzaak
      vars:
        db_host: "{{ db.privateIp }}"
        db_port: "{{ db.port }}"
        db_name: "{{ openzaak_db_name }}"
        db_username: "{{ openzaak_db_username }}"
        db_password: "{{ openzaak_db_password }}"

    - role: opennotificaties
      vars:
        opennotificaties_db_host: "{{ db.privateIp }}"
        opennotificaties_db_port: "{{ db.port }}"
