---

- name: Initialize a Kubernetes cluster
  hosts: localhost

  vars:
    # FIXME
    ansible_python_interpreter: /home/bbt/.virtualenvs/open-zaak/bin/python

  tasks:
    - debug: msg="hello world"
