---

- name: Deploy the Open Zaak apps in the cluster
  hosts: localhost

  vars_files:
    - vars/db_credentials.yml
    - vars/openzaak.yml
    - vars/opennotificaties.yml
    - vars/nlx.yml

  roles:
    - role: openzaak
      vars:
        openzaak_domain: test.openzaak.nl
        openzaak_db_host: "{{ db.privateIp }}"
        openzaak_db_port: "{{ db.port }}"
        openzaak_replicas: 3
      tags:
        - openzaak

    - role: opennotificaties
      vars:
        opennotificaties_db_host: "{{ db.privateIp }}"
        opennotificaties_db_port: "{{ db.port }}"

    - role: nlx
      vars:
        nlx_instance: test
        nlx_inway_self_address: inway.openzaak.nl
        nlx_inway_services:
          - name: openzaak-zaken
            endpoint_url: https://{{ openzaak_domain }}/zaken/api/v1
            documentation_url: https://{{ openzaak_domain }}/zaken/
            authorization_model: none
            api_specification_document_url: https://{{ openzaak_domain }}/zaken/api/v1/schema/openapi.json

          - name: openzaak-documenten
            endpoint_url: https://{{ openzaak_domain }}/documenten/api/v1
            documentation_url: https://{{ openzaak_domain }}/documenten/
            authorization_model: none
            api_specification_document_url: https://{{ openzaak_domain }}/documenten/api/v1/schema/openapi.json

          - name: openzaak-catalogi
            endpoint_url: https://{{ openzaak_domain }}/catalogi/api/v1
            documentation_url: https://{{ openzaak_domain }}/catalogi/
            authorization_model: none
            api_specification_document_url: https://{{ openzaak_domain }}/catalogi/api/v1/schema/openapi.json

          - name: openzaak-besluiten
            endpoint_url: https://{{ openzaak_domain }}/besluiten/api/v1
            documentation_url: https://{{ openzaak_domain }}/besluiten/
            authorization_model: none
            api_specification_document_url: https://{{ openzaak_domain }}/besluiten/api/v1/schema/openapi.json

          - name: openzaak-authorizations
            endpoint_url: https://{{ openzaak_domain }}/authorizations/api/v1
            documentation_url: https://{{ openzaak_domain }}/authorizations/
            authorization_model: none
            api_specification_document_url: https://{{ openzaak_domain }}/authorizations/api/v1/schema/openapi.json
      tags:
        - nlx
