---

- name: Deploy Open Zaak on a single server
  hosts: all

  collections:
    - open_zaak.deploy

  vars_files:
    - vars/postgres.yml
    - vars/open-zaak.yml

  vars:
    # postgresql vars - from secrets
    postgresql_users:
      - name: "{{ openzaak_db_username }}"
        password: "{{ openzaak_db_password }}"
        port: "{{ openzaak_db_port }}"
    postgresql_databases:
      - name: "{{ openzaak_db_name }}"
        owner: "{{ openzaak_db_username }}"
        port: "{{ openzaak_db_port }}"

    # certbot vars
    certbot_admin_email: support@maykinmedia.nl
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services: []
    # certbot_create_standalone_stop_services: ['nginx']
    certbot_certs:
      - domains:
          - "{{ openzaak_domain }}"

    # nginx vars
    ssl_enabled: "{{ certbot_create_if_missing | bool }}"
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: templates/openzaak.conf.j2
        conf_file_name: default.conf
        conf_file_location: /etc/nginx/conf.d/

  roles:
    - role: debian_setup

    - role: geerlingguy.postgresql
      tags:
        - db

    - role: geerlingguy.docker

    - role: geerlingguy.certbot

    - role: app_database
      vars:
        app_db_provision_user: no
        app_db_provision_database: no
        app_db_become_user: postgres

        app_db_host: ''
        app_db_port: "{{ openzaak_db_port }}"
        app_db_name: "{{ openzaak_db_name }}"
        app_db_extensions:
          - postgis
          - pg_trgm
      tags:
        - app_db

    - role: open_zaak_docker
      vars:
        openzaak_version: '0.9.0'  # see https://github.com/open-zaak/open-zaak/releases
      tags:
        - replicas

    - role: nginxinc.nginx
      vars:
        # set by the open_zaak_docker role while provisioning the docker volume
        openzaak_volume_path: "{{ openzaak_volume.volume.Mountpoint }}"
      tags:
        - replicas
