---

- name: Create the PVC
  k8s:
    state: present
    name: openzaak-test
    namespace: "{{ namespace }}"
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: ""
        resources:
          requests:
            storage: "{{ openzaak_storage }}"

