---

# Install the Traefik ingress route(s)

# HTTP

- name: Set up HTTP -> HTTPS middleware
  k8s:
    state: present
    name: openzaak-https-redirect
    namespace: "{{ namespace }}"
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: Middleware
      spec:
        redirectScheme:
          scheme: https

- name: Install HTTP Ingress Route
  k8s:
    state: present
    name: openzaak-http
    namespace: "{{ namespace }}"
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      spec:
        entryPoints:
          - web
        routes:
        - match: Host(`{{ domain }}`)
          kind: Rule
          services:
          - name: nginx
            port: 80
          middlewares:
            - name: openzaak-https-redirect

# HTTPS

- name: Set up HTTPS HSTS Header
  k8s:
    state: present
    name: openzaak-https-hsts
    namespace: "{{ namespace }}"
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: Middleware
      spec:
        headers:
          stsSeconds: 31536000
          stsIncludeSubdomains: yes
          stsPreload: yes

- name: Install HTTPS Ingress Route
  k8s:
    state: present
    name: openzaak-https
    namespace: "{{ namespace }}"
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      spec:
        entryPoints:
          - websecure
        routes:
        - match: Host(`{{ domain }}`)
          kind: Rule
          services:
          - name: nginx
            port: 80
          middlewares:
            - name: openzaak-https-hsts
        tls:
          certResolver: default
          options:
            namespace: default
            name: default
