---

# Install the Traefik ingress route(s)

- name: Install HTTP Ingress Route
  k8s:
    state: present
    name: openzaak-http
    namespace: "{{ namespace }}"
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      spec:
        entryPoints:
          - web
        routes:
        - match: Host(`{{ domain }}`)
          kind: Rule
          services:
          - name: nginx
            port: 80

- name: Install HTTPS Ingress Route
  k8s:
    state: present
    name: openzaak-https
    namespace: "{{ namespace }}"
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      spec:
        entryPoints:
          - websecure
        routes:
        - match: Host(`{{ domain }}`)
          kind: Rule
          services:
          - name: nginx
            port: 80
        tls:
          certResolver: default
